### PR TITLE
enhancement: additional keydown codes

### PR DESCRIPTION
**Pull request by jacekkarczmarczyk**
It will allowed to use more key codes, ex. `trigger('keydown.home')`

### CODE REVIEW

**Comment by eddyerburgh** [comment]
Thanks 😀

**Comment by jacekkarczmarczyk** [comment]
will you add it also to vue-test-utils?

**Comment by eddyerburgh** [comment]
Yes when I get around to it, unless you've able to make a PR?

**Comment by jacekkarczmarczyk** [comment]
I'll do, btw do you have a minute on on a vuetify chat?

**Comment by eddyerburgh** [comment]
Yeah, I'll log in now

**Pull request merged**
