### PR TITLE
Use wrapper in slots

### PR DESCRIPTION
**Pull request by nekosaur**
Tried the simplest thing I could think of, and it seem to have worked? :)

### CODE REVIEW

**Comment by eddyerburgh** [comment]
Nice 🔥

There's a types file now, if you know TypeScript, could you add the option to pass a vnode to slots. The file is in types/index.d.ts, and could you write a test in types/test/mount.spec?

If you don't know TS, I'll do it some time, probably tomorrow

**Comment by nekosaur** [comment]
I've actually never used TypeScript. But if you feel like you don't have the time, I could take a stab at it.

**Comment by eddyerburgh** [comment]
I'll merge and make the changes in master before releasing 👌

**Comment by eddyerburgh** [comment]
I've released in 3.2.0

**Pull request merged**
